import { useMemo,useState } from "react";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { ArrowDown,ArrowUp,Loader2,MessagesSquare,Plus,Trash2 } from "lucide-react";
import { toast } from "sonner";
import { OperationalInputterCard } from "@/components/OperationalInputterCard";
import { Button } from "@/components/ui/button";
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
import { Dialog,DialogContent,DialogFooter,DialogHeader,DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs,TabsContent,TabsList,TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { useBusinessStructure } from "@/hooks/useBusinessStructure";
import { useOperationalInputter } from "@/hooks/useOperationalInputter";
import { jakartaToday } from "@/lib/businessPeriod";
import { createInterview,fetchActiveInterviewForm,fetchInterviews,indonesianDayName,orderAnswers,publishInterviewForm,updateInterview,type CustomerInterview,type InterviewQuestion } from "@/lib/customerInterviews";

export function CustomerInterviewManager(){
 const {outlet,isLoading:structureLoading,error:structureError}=useBusinessStructure(),outletId=outlet?.id??null;
 const inputter=useOperationalInputter(outletId,"interviews"),client=useQueryClient();
 const [month,setMonth]=useState(jakartaToday().slice(0,7)),[editor,setEditor]=useState<CustomerInterview|null|undefined>(undefined),[config,setConfig]=useState(false);
 const form=useQuery({queryKey:["customer-interview-form",outletId],enabled:Boolean(outletId),queryFn:()=>fetchActiveInterviewForm(outletId!)});
 const history=useQuery({queryKey:["customer-interviews",outletId,month],enabled:Boolean(outletId),queryFn:()=>fetchInterviews(outletId!,month)});
 if(structureLoading)return <State text="Memuat modul wawancara..."/>;if(structureError)return <State text="Data Outlet gagal dimuat."/>;
 return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Wawancara Orang Tua</h1><p className="text-muted-foreground">Formulir dinamis dengan riwayat versi yang tetap utuh.</p></div>
  <OperationalInputterCard outletId={outletId} section="interviews"/>
  <Tabs defaultValue="data"><TabsList><TabsTrigger value="data">Data Wawancara</TabsTrigger><TabsTrigger value="questions">Atur Pertanyaan</TabsTrigger></TabsList>
   <TabsContent value="data" className="space-y-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><Label htmlFor="month">Periode</Label><Input id="month" type="month" value={month} onChange={e=>setMonth(e.target.value)} /></div><div className="flex items-center gap-3"><span className="text-sm">Data Terinput: <b>{history.data?.length??0}</b></span><Button disabled={!inputter.name||!form.data} onClick={()=>setEditor(null)}><Plus className="mr-2 h-4 w-4"/>Tambah Wawancara</Button></div></div>
    {!inputter.name?<p className="rounded-md border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900">Atur nama penginput terlebih dahulu.</p>:null}
    {form.isError?<State text="Pertanyaan gagal dimuat."/>:form.isSuccess&&!form.data?<State text="Formulir wawancara aktif tidak tersedia. Hubungi pengelola database."/>:history.isLoading?<State text="Memuat data wawancara..."/>:history.isError?<State text="Data wawancara gagal dimuat."/>:history.data?.length?<div className="space-y-2">{history.data.map(row=><button className="grid w-full grid-cols-2 gap-2 rounded-lg border p-4 text-left hover:bg-muted md:grid-cols-5" key={row.id} onClick={()=>setEditor(row)}><span>{row.interview_date}</span><span>{indonesianDayName(row.interview_date)}</span><span>{row.visit_time.slice(0,5)} WIB</span><span>{row.inputter_name}</span><span>Versi {row.customer_interview_form_versions.version_number}</span></button>)}</div>:<State text="Belum ada data wawancara."/>}
   </TabsContent>
   <TabsContent value="questions"><Card><CardHeader><CardTitle>Versi Aktif: {form.data?.version_number??"—"}</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm text-muted-foreground">Perubahan pertanyaan hanya berlaku untuk wawancara baru. Data wawancara lama tetap menggunakan versi sebelumnya.</p><Button disabled={!form.data} onClick={()=>setConfig(true)}>Atur Pertanyaan</Button></CardContent></Card></TabsContent>
  </Tabs>
  {editor!==undefined&&form.data?<InterviewDialog value={editor} activeQuestions={form.data.questions} inputterName={inputter.name} onClose={()=>setEditor(undefined)} onSave={async(date,time,answers)=>{if(!outletId)throw new Error("Outlet tidak tersedia.");if(editor){await updateInterview(editor.id,{interviewDate:date,visitTime:time,answers});}else{const session=await inputter.ensureValidSession();await createInterview(outletId,session.sessionId,{interviewDate:date,visitTime:time,answers});}await client.invalidateQueries({queryKey:["customer-interviews"]});}}/>:null}
  {config&&form.data?<QuestionDialog questions={form.data.questions} onClose={()=>setConfig(false)} onPublish={async questions=>{await publishInterviewForm(outletId!,questions);await client.invalidateQueries({queryKey:["customer-interview-form"]});}}/>:null}
 </div>;
}
function State({text}:{text:string}){return <div className="rounded-lg border p-8 text-center text-sm text-muted-foreground">{text}</div>}
function InterviewDialog({value,activeQuestions,inputterName,onClose,onSave}:{value:CustomerInterview|null;activeQuestions:InterviewQuestion[];inputterName:string|null;onClose:()=>void;onSave:(d:string,t:string,a:ReturnType<typeof orderAnswers>)=>Promise<void>}){
 const questions=useMemo(()=>value?[...value.customer_interview_form_versions.customer_interview_questions].sort((a,b)=>a.sort_order-b.sort_order):activeQuestions,[value,activeQuestions]);
 const [date,setDate]=useState(value?.interview_date??jakartaToday()),[time,setTime]=useState(value?.visit_time.slice(0,5)??""),[answers,setAnswers]=useState<Record<string,string>>(()=>Object.fromEntries((value?.customer_interview_answers??[]).map(a=>[a.question_id,a.answer_text??""]))),[saving,setSaving]=useState(false);
 const historicalName=value?.inputter_name??inputterName??"";
 const save=async()=>{if(!date||!time||!historicalName)return toast.error("Tanggal, jam, dan nama pelaksana wajib tersedia.");setSaving(true);try{await onSave(date,time,orderAnswers(questions,answers));toast.success(value?"Wawancara diperbarui.":"Wawancara tersimpan.");onClose();}catch(e){toast.error(e instanceof Error?e.message:"Wawancara gagal disimpan.");}finally{setSaving(false)}};
 return <Dialog open onOpenChange={o=>!o&&!saving&&onClose()}><DialogContent className="max-h-[90vh] max-w-3xl overflow-y-auto"><DialogHeader><DialogTitle>{value?"Detail & Edit":"Tambah"} Wawancara {value?`— Versi ${value.customer_interview_form_versions.version_number}`:""}</DialogTitle></DialogHeader><section className="grid gap-4 sm:grid-cols-2"><h3 className="sm:col-span-2 font-semibold">Informasi Wawancara</h3><Field label="Hari"><Input readOnly value={indonesianDayName(date)}/></Field><Field label="Tanggal"><Input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></Field><Field label="Nama Pelaksana Tugas"><Input readOnly value={historicalName}/></Field><Field label="Jam Berkunjung (WIB)"><Input type="time" required value={time} onChange={e=>setTime(e.target.value)}/></Field></section><section className="space-y-4"><h3 className="font-semibold">Data Hasil Wawancara Orang Tua</h3>{questions.map((q,i)=><Field key={q.id} label={`${i+1}. ${q.question_text}`}><Textarea value={answers[q.id]??""} onChange={e=>setAnswers(a=>({...a,[q.id]:e.target.value}))}/></Field>)}</section><DialogFooter><Button variant="outline" onClick={onClose}>Batal</Button><Button disabled={saving} onClick={save}>{saving?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:null}Simpan</Button></DialogFooter></DialogContent></Dialog>;
}
function QuestionDialog({questions,onClose,onPublish}:{questions:InterviewQuestion[];onClose:()=>void;onPublish:(q:string[])=>Promise<void>}){const [draft,setDraft]=useState(questions.map(q=>q.question_text)),[saving,setSaving]=useState(false);const move=(i:number,d:number)=>setDraft(a=>{const n=[...a],[x]=n.splice(i,1);n.splice(i+d,0,x);return n});const save=async()=>{setSaving(true);try{await onPublish(draft);toast.success("Versi pertanyaan baru diterbitkan.");onClose();}catch(e){toast.error(e instanceof Error?e.message:"Versi gagal diterbitkan.");}finally{setSaving(false)}};return <Dialog open onOpenChange={o=>!o&&!saving&&onClose()}><DialogContent className="max-h-[90vh] max-w-3xl overflow-y-auto"><DialogHeader><DialogTitle>Atur Pertanyaan</DialogTitle></DialogHeader><p className="text-sm text-muted-foreground">Perubahan pertanyaan hanya berlaku untuk wawancara baru. Data wawancara lama tetap menggunakan versi sebelumnya.</p>{draft.map((q,i)=><div className="flex gap-2" key={i}><span className="pt-2">{i+1}.</span><Textarea value={q} onChange={e=>setDraft(a=>a.map((v,x)=>x===i?e.target.value:v))}/><div className="flex flex-col"><Button size="icon" variant="ghost" disabled={!i} onClick={()=>move(i,-1)}><ArrowUp/></Button><Button size="icon" variant="ghost" disabled={i===draft.length-1} onClick={()=>move(i,1)}><ArrowDown/></Button><Button size="icon" variant="ghost" onClick={()=>setDraft(a=>a.filter((_,x)=>x!==i))}><Trash2/></Button></div></div>)}<Button variant="outline" onClick={()=>setDraft(a=>[...a,""])}><Plus className="mr-2 h-4 w-4"/>Tambah Pertanyaan</Button><DialogFooter><Button variant="outline" onClick={onClose}>Batal</Button><Button disabled={saving||!draft.length||draft.some(q=>!q.trim())} onClick={save}>Simpan & Gunakan Versi Baru</Button></DialogFooter></DialogContent></Dialog>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-2"><Label>{label}</Label>{children}</div>}
