/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAnalitikProdukRouteImport } from './routes/_authenticated/analitik-produk'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedItemPengeluaranRouteImport } from './routes/_authenticated/item-pengeluaran'
import { Route as AuthenticatedKategoriPengeluaranRouteImport } from './routes/_authenticated/kategori-pengeluaran'
import { Route as AuthenticatedKategoriPenjualanRouteImport } from './routes/_authenticated/kategori-penjualan'
import { Route as AuthenticatedPengeluaranRouteImport } from './routes/_authenticated/pengeluaran'
import { Route as AuthenticatedPenggunaRouteImport } from './routes/_authenticated/pengguna'
import { Route as AuthenticatedPenjualanRouteImport } from './routes/_authenticated/penjualan'
import { Route as AuthenticatedProdukRouteImport } from './routes/_authenticated/produk'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalitikProdukRoute =
  AuthenticatedAnalitikProdukRouteImport.update({
    id: '/analitik-produk',
    path: '/analitik-produk',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedItemPengeluaranRoute =
  AuthenticatedItemPengeluaranRouteImport.update({
    id: '/item-pengeluaran',
    path: '/item-pengeluaran',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKategoriPengeluaranRoute =
  AuthenticatedKategoriPengeluaranRouteImport.update({
    id: '/kategori-pengeluaran',
    path: '/kategori-pengeluaran',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKategoriPenjualanRoute =
  AuthenticatedKategoriPenjualanRouteImport.update({
    id: '/kategori-penjualan',
    path: '/kategori-penjualan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPengeluaranRoute =
  AuthenticatedPengeluaranRouteImport.update({
    id: '/pengeluaran',
    path: '/pengeluaran',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPenggunaRoute = AuthenticatedPenggunaRouteImport.update({
  id: '/pengguna',
  path: '/pengguna',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPenjualanRoute = AuthenticatedPenjualanRouteImport.update({
  id: '/penjualan',
  path: '/penjualan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdukRoute = AuthenticatedProdukRouteImport.update({
  id: '/produk',
  path: '/produk',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analitik-produk': typeof AuthenticatedAnalitikProdukRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/item-pengeluaran': typeof AuthenticatedItemPengeluaranRoute
  '/kategori-pengeluaran': typeof AuthenticatedKategoriPengeluaranRoute
  '/kategori-penjualan': typeof AuthenticatedKategoriPenjualanRoute
  '/pengeluaran': typeof AuthenticatedPengeluaranRoute
  '/pengguna': typeof AuthenticatedPenggunaRoute
  '/penjualan': typeof AuthenticatedPenjualanRoute
  '/produk': typeof AuthenticatedProdukRoute
  '/profil': typeof AuthenticatedProfilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analitik-produk': typeof AuthenticatedAnalitikProdukRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/item-pengeluaran': typeof AuthenticatedItemPengeluaranRoute
  '/kategori-pengeluaran': typeof AuthenticatedKategoriPengeluaranRoute
  '/kategori-penjualan': typeof AuthenticatedKategoriPenjualanRoute
  '/pengeluaran': typeof AuthenticatedPengeluaranRoute
  '/pengguna': typeof AuthenticatedPenggunaRoute
  '/penjualan': typeof AuthenticatedPenjualanRoute
  '/produk': typeof AuthenticatedProdukRoute
  '/profil': typeof AuthenticatedProfilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/analitik-produk': typeof AuthenticatedAnalitikProdukRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/item-pengeluaran': typeof AuthenticatedItemPengeluaranRoute
  '/_authenticated/kategori-pengeluaran': typeof AuthenticatedKategoriPengeluaranRoute
  '/_authenticated/kategori-penjualan': typeof AuthenticatedKategoriPenjualanRoute
  '/_authenticated/pengeluaran': typeof AuthenticatedPengeluaranRoute
  '/_authenticated/pengguna': typeof AuthenticatedPenggunaRoute
  '/_authenticated/penjualan': typeof AuthenticatedPenjualanRoute
  '/_authenticated/produk': typeof AuthenticatedProdukRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/analitik-produk'
    | '/dashboard'
    | '/item-pengeluaran'
    | '/kategori-pengeluaran'
    | '/kategori-penjualan'
    | '/pengeluaran'
    | '/pengguna'
    | '/penjualan'
    | '/produk'
    | '/profil'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/analitik-produk'
    | '/dashboard'
    | '/item-pengeluaran'
    | '/kategori-pengeluaran'
    | '/kategori-penjualan'
    | '/pengeluaran'
    | '/pengguna'
    | '/penjualan'
    | '/produk'
    | '/profil'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/analitik-produk'
    | '/_authenticated/dashboard'
    | '/_authenticated/item-pengeluaran'
    | '/_authenticated/kategori-pengeluaran'
    | '/_authenticated/kategori-penjualan'
    | '/_authenticated/pengeluaran'
    | '/_authenticated/pengguna'
    | '/_authenticated/penjualan'
    | '/_authenticated/produk'
    | '/_authenticated/profil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analitik-produk': {
      id: '/_authenticated/analitik-produk'
      path: '/analitik-produk'
      fullPath: '/analitik-produk'
      preLoaderRoute: typeof AuthenticatedAnalitikProdukRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/item-pengeluaran': {
      id: '/_authenticated/item-pengeluaran'
      path: '/item-pengeluaran'
      fullPath: '/item-pengeluaran'
      preLoaderRoute: typeof AuthenticatedItemPengeluaranRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kategori-pengeluaran': {
      id: '/_authenticated/kategori-pengeluaran'
      path: '/kategori-pengeluaran'
      fullPath: '/kategori-pengeluaran'
      preLoaderRoute: typeof AuthenticatedKategoriPengeluaranRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kategori-penjualan': {
      id: '/_authenticated/kategori-penjualan'
      path: '/kategori-penjualan'
      fullPath: '/kategori-penjualan'
      preLoaderRoute: typeof AuthenticatedKategoriPenjualanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pengeluaran': {
      id: '/_authenticated/pengeluaran'
      path: '/pengeluaran'
      fullPath: '/pengeluaran'
      preLoaderRoute: typeof AuthenticatedPengeluaranRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pengguna': {
      id: '/_authenticated/pengguna'
      path: '/pengguna'
      fullPath: '/pengguna'
      preLoaderRoute: typeof AuthenticatedPenggunaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/penjualan': {
      id: '/_authenticated/penjualan'
      path: '/penjualan'
      fullPath: '/penjualan'
      preLoaderRoute: typeof AuthenticatedPenjualanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produk': {
      id: '/_authenticated/produk'
      path: '/produk'
      fullPath: '/produk'
      preLoaderRoute: typeof AuthenticatedProdukRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalitikProdukRoute: typeof AuthenticatedAnalitikProdukRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedItemPengeluaranRoute: typeof AuthenticatedItemPengeluaranRoute
  AuthenticatedKategoriPengeluaranRoute: typeof AuthenticatedKategoriPengeluaranRoute
  AuthenticatedKategoriPenjualanRoute: typeof AuthenticatedKategoriPenjualanRoute
  AuthenticatedPengeluaranRoute: typeof AuthenticatedPengeluaranRoute
  AuthenticatedPenggunaRoute: typeof AuthenticatedPenggunaRoute
  AuthenticatedPenjualanRoute: typeof AuthenticatedPenjualanRoute
  AuthenticatedProdukRoute: typeof AuthenticatedProdukRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalitikProdukRoute: AuthenticatedAnalitikProdukRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedItemPengeluaranRoute: AuthenticatedItemPengeluaranRoute,
  AuthenticatedKategoriPengeluaranRoute: AuthenticatedKategoriPengeluaranRoute,
  AuthenticatedKategoriPenjualanRoute: AuthenticatedKategoriPenjualanRoute,
  AuthenticatedPengeluaranRoute: AuthenticatedPengeluaranRoute,
  AuthenticatedPenggunaRoute: AuthenticatedPenggunaRoute,
  AuthenticatedPenjualanRoute: AuthenticatedPenjualanRoute,
  AuthenticatedProdukRoute: AuthenticatedProdukRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
